---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git-repo.yaml
  - git-secret.yaml
  - flux-kustomization.yaml
  - ns.yaml
  - sa.yaml
  - role-binding.yaml
  - app-iam.yaml
  - app-sa.yaml